#!/bin/bash
# Commands to check storage directory structure and permissions on production

echo "=== Storage Directory Structure ==="
echo ""
echo "Check if directories exist:"
echo "ls -la /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/"
echo ""
echo "Check tts directory (prompts - working):"
echo "ls -la /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/tts/"
echo ""
echo "Check vocabulary-audio directory (vocabulary - not working):"
echo "ls -la /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio/"
echo ""
echo "Check directory permissions:"
echo "stat /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/"
echo "stat /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/tts/"
echo "stat /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio/"
echo ""
echo "Check who owns the directories:"
echo "ls -ld /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/"
echo "ls -ld /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/tts/"
echo "ls -ld /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio/"
echo ""
echo "Check if vocabulary-audio directory exists:"
echo "test -d /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio && echo 'Directory exists' || echo 'Directory does NOT exist'"
echo ""
echo "Try to create the directory manually:"
echo "mkdir -p /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio"
echo "chmod 755 /home/1428986.cloudwaysapps.com/pefnmxyext/public_html/storage/app/public/vocabulary-audio"

